services:
  config_devel.filestorage_subscriber:
    class: Drupal\config_devel\EventSubscriber\ConfigDevelFileStorageSubscriber
    arguments: ['@config_devel.filestorage', '@config.storage.installer', '@settings', '@config.manager']
    tags:
      - { name: event_subscriber }
  config_devel.filestorage:
    class: Drupal\Core\Config\FileStorage
    factory_class: Drupal\config_devel\Config\FileStorageFactory
    factory_method: create
    arguments: ['@settings', '@kernel']
