services:
  config_devel.writeback_subscriber:
    class: Drupal\config_devel\EventSubscriber\ConfigDevelAutoExportSubscriber
    arguments: ['@config.factory', '@config.manager', '@config.storage.file']
    tags:
      - { name: event_subscriber }
  config_devel.reinstall_subscriber:
    class: Drupal\config_devel\EventSubscriber\ConfigDevelReinstallSubscriber
    arguments: ['@config.manager', '@config.factory', '@entity.manager']
    tags:
      - { name: event_subscriber }
